// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attendance_api.Data;

#nullable disable

namespace attendance_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214041520_UpdatedModels_Fresh")]
    partial class UpdatedModels_Fresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("attendance_api.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendanceid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("attendancedate");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("InBiometric")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inbiometric");

                    b.Property<decimal?>("InLatitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("inlatitude");

                    b.Property<string>("InLocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("inlocationaddress");

                    b.Property<decimal?>("InLongitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("inlongitude");

                    b.Property<string>("InSelfie")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("inselfie");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time")
                        .HasColumnName("intime");

                    b.Property<DateTime?>("InTimeDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("intimedatetime");

                    b.Property<string>("OutBiometric")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outbiometric");

                    b.Property<decimal?>("OutLatitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("outlatitude");

                    b.Property<string>("OutLocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("outlocationaddress");

                    b.Property<decimal?>("OutLongitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("outlongitude");

                    b.Property<string>("OutSelfie")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("outselfie");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time")
                        .HasColumnName("outtime");

                    b.Property<DateTime?>("OutTimeDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("outtimedatetime");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("totalhours");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedon");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("AttendanceId");

                    b.HasIndex("UserId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("attendance");
                });

            modelBuilder.Entity("attendance_api.Models.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("holidayid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("holidaydate");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("holidayname");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.HasKey("HolidayId");

                    b.HasIndex("HolidayDate")
                        .IsUnique();

                    b.ToTable("holidays");
                });

            modelBuilder.Entity("attendance_api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("RequiresSelfie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("requiresselfie");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rolename");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("attendance_api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ConfirmPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("confirmpassword");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("deviceid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastseen");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("macaddress");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedOn = new DateTime(2026, 2, 14, 9, 45, 18, 480, DateTimeKind.Local).AddTicks(6160),
                            Email = "admin@attendance.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$ncaFWkdH5/SEu2JDk.vonuDkZlGH.7G6UzTWIVDxQFjivzTBGiE9q",
                            Role = "admin",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("attendance_api.Models.Attendance", b =>
                {
                    b.HasOne("attendance_api.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("attendance_api.Models.User", b =>
                {
                    b.HasOne("attendance_api.Models.Role", "RoleEntity")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RoleEntity");
                });

            modelBuilder.Entity("attendance_api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("attendance_api.Models.User", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
