// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attendance_api.Data;

#nullable disable

namespace attendance_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208194415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("attendance_api.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendanceid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("attendancedate");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("InLatitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("inlatitude");

                    b.Property<string>("InLocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("inlocationaddress");

                    b.Property<decimal?>("InLongitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("inlongitude");

                    b.Property<string>("InSelfie")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("inselfie");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time")
                        .HasColumnName("intime");

                    b.Property<DateTime?>("InTimeDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("intimedatetime");

                    b.Property<decimal?>("OutLatitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("outlatitude");

                    b.Property<string>("OutLocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("outlocationaddress");

                    b.Property<decimal?>("OutLongitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("outlongitude");

                    b.Property<string>("OutSelfie")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("outselfie");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time")
                        .HasColumnName("outtime");

                    b.Property<DateTime?>("OutTimeDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("outtimedatetime");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("totalhours");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedon");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("AttendanceId");

                    b.HasIndex("UserId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("attendance");
                });

            modelBuilder.Entity("attendance_api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("deviceid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastseen");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedOn = new DateTime(2026, 2, 9, 1, 14, 13, 917, DateTimeKind.Local).AddTicks(5331),
                            Email = "admin@attendance.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$of1J2CuwNhVUzg4X/XXMjej9L2yKqFqVBc1.whkvNX74S777K.aHa",
                            Role = "admin",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("attendance_api.Models.Attendance", b =>
                {
                    b.HasOne("attendance_api.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("attendance_api.Models.User", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
